# Generated by Django 2.0 on 2018-01-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180103_2313'),
        ('watchlists', '0002_auto_20171226_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_watched', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='movies',
            new_name='_movies',
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.WatchList'),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('movie', 'watchlist')},
        ),
    ]
