# Generated by Django 2.0 on 2018-01-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20171226_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='moviedb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
